# Generated by Django 5.2 on 2025-06-03 09:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('icon_name', models.CharField(blank=True, max_length=100, null=True)),
                ('category', models.CharField(choices=[('VEG', 'Vegetable'), ('FRUIT', 'Fruit'), ('LEGUME', 'Legumes & Beans'), ('MUSH', 'Mushroom'), ('GRAIN', 'Grains & Cereals'), ('BAKED', 'Baked Goods'), ('PORK', 'Pork'), ('CHICKEN', 'Chicken'), ('BEEF', 'Beef'), ('SEAFOOD', 'Seafood'), ('EGG', 'Eggs'), ('MEAT', 'Other Meat'), ('DAIRY', 'Dairy'), ('H&S', 'Herbs & Spices'), ('COND', 'Condiments & Sauces'), ('BEV', 'Beverages'), ('ALCO', 'Alcohol'), ('OTHER', 'Other')], max_length=20)),
                ('expiration_date', models.DateField()),
                ('quantity', models.FloatField()),
                ('unit', models.CharField(choices=[('g', 'Gram'), ('kg', 'Kilogram'), ('oz', 'Ounce'), ('lb', 'Pound'), ('ml', 'Milliliter'), ('l', 'Liter'), ('tsp', 'Teaspoon'), ('tbsp', 'Tablespoon'), ('cup', 'Cup'), ('pc', 'Piece'), ('bunch', 'Bunch'), ('slice', 'Slice'), ('pack', 'Pack'), ('bottle', 'Bottle'), ('can', 'Can')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dietary_preferences', models.JSONField(default=list, help_text="List of dietary preferences (e.g., ['vegetarian', 'gluten-free'])")),
                ('saved_recipes', models.JSONField(default=list, help_text='List of recipe IDs saved by the user')),
                ('fridge_inventory', models.JSONField(default=list, help_text="List of ingredients in the user's fridge (e.g., ['chicken', 'tomatoes'])")),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='account', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Account',
                'verbose_name_plural': 'User Accounts',
            },
        ),
    ]
