# Generated by Django 5.2 on 2025-06-05 00:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_ingredient_options_ingredient_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('type', models.CharField(choices=[('dessert', 'Dessert'), ('appetizer', 'Appetizer'), ('main_course', 'Main Course'), ('side_dish', 'Side Dish'), ('snack', 'Snack'), ('beverage', 'Beverage')], max_length=20)),
                ('cuisine', models.CharField(choices=[('chinese', 'Chinese'), ('indian', 'Indian'), ('italian', 'Italian'), ('mexican', 'Mexican'), ('middle_eastern', 'Middle Eastern'), ('fusion', 'Fusion')], max_length=20)),
                ('time_required', models.CharField(choices=[('under_15', '< 15 minutes'), ('15_30', '15-30 minutes'), ('30_60', '30-60 minutes'), ('over_60', ' > 60 minutes')], max_length=20)),
                ('nutritional_style', models.CharField(choices=[('healthy', 'Healthy'), ('low_carb', 'Low Carb'), ('high_protein', 'High Protein'), ('whole_foods', 'Whole Foods'), ('vegan', 'Vegan'), ('vegetarian', 'Vegetarian')], max_length=20)),
                ('ingredients', models.JSONField(default=list, help_text="List of ingredients with their measurements (e.g., [{'name': 'flour', 'quantity': 2, 'unit': 'cup'}])")),
                ('steps', models.JSONField(default=list, help_text='List of cooking steps in order')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='recipes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
