# Generated by Django 5.2 on 2025-06-05 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_recipe'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='allergies',
            field=models.JSONField(default=list, help_text="List of allergies (e.g., ['milk', 'peanuts'])"),
        ),
    ]
