# Generated by Django 5.2 on 2025-06-05 02:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_remove_account_fridge_inventory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='cuisine',
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='nutritional_style',
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='time_required',
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='type',
        ),
    ]
